version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - revive
    - unconvert
  settings:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    errcheck:
      check-blank: true
    gocyclo:
      # minimal code complexity to report, 30 by default
      min-complexity: 15
    govet:
      enable:
        # report about shadowed variables
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
