# .github/workflows/release.yml
name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v5.0.1 (2025-11-13)
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Go
        # v6.3.0 (2026-02-25)
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version: "1.25"
          cache: false
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        # v7.0.0 (2026-02-09)
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Build Changelog
        id: github_release_changelog
        # v5.4.1 (2025-07-13)
        uses: mikepenz/release-changelog-builder-action@c9dc8369bccbc41e0ac887f8fd674f5925d315f7
        with:
          configurationJson: |
            {
                "categories": [
                    {
                      "title": "## 🚀 Features",
                      "labels": ["feature","feat","Feature","Feat"]
                    },
                    {
                      "title": "## 🐛 Fixes",
                      "labels": ["fix","fixes", "bug", "bugs", "Fix", "Fixes", "Bug", "Bugs"]
                    },
                    {
                      "title": "## 🧪 Tests",
                      "labels": ["test", "tests", "Test", "Tests"]
                    },
                    {
                      "title": "## 📦 Uncategorized",
                      "labels": []
                    }
                  ],
                "label_extractor": [
                    {
                        "pattern": "^.?(build|chore|ci|cleanup|docs|feat|fix|misc|perf|refactor|revert|style|test|tests).?.*",
                        "target": "$1",
                        "method": "regexr",
                        "on_property": "title"
                    }
                ]
            }
      - name: Update Release
        # v0.6.0 (2024-03-14)
        uses: mikepenz/action-gh-release@9a604afa5167a745eab07256a54e2f578a1a0c5e
        with:
          tag_name: ${{ github.event.inputs.to_tag }}
          body: ${{steps.github_release_changelog.outputs.changelog}}
